Repository project-topaz/topaz, pull requests merged in 2020-10, with the labels that each got.

#1229 Implements Subtle Blow II
  scripts/globals/status.lua
  sql/item_mods.sql
  src/map/modifier.h
  src/map/utils/battleutils.cpp
Labels: reviewed

#1263 Wyvern status removal breaths should prioritize master and breath IDs are incorrect
  scripts/globals/pets/wyvern.lua
Labels: reviewed

#1295 Lindwurm drops were not accurate for skin
  sql/mob_droplist.sql
Labels: approved, reviewed

#1243 Notoriety Container
  scripts/globals/status.lua
  src/map/ai/helpers/targetfind.h
  src/map/enmity_container.cpp
  src/map/entities/battleentity.cpp
  src/map/entities/battleentity.h
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/notoriety_container.cpp
  src/map/notoriety_container.h
  src/map/status_effect_container.cpp
  src/map/zone.cpp
  win32/vcxproj/topaz_game.vcxproj
  win32/vcxproj/topaz_game.vcxproj.filters
Labels: improvement

#1279 Zilart "Return to Delkfutt's Tower" CS in lower tower optional
  scripts/zones/Stellar_Fulcrum/Zone.lua
Labels: reviewed

#1267 Optional scenes for all San d'Oria missions
  scripts/zones/Chateau_dOraguille/IDs.lua
  scripts/zones/Chateau_dOraguille/Zone.lua
  scripts/zones/Chateau_dOraguille/npcs/Aramaviont.lua
  scripts/zones/Chateau_dOraguille/npcs/Arsha.lua
  scripts/zones/Chateau_dOraguille/npcs/Chupaile.lua
  scripts/zones/Chateau_dOraguille/npcs/Curilla.lua
  scripts/zones/Chateau_dOraguille/npcs/Halver.lua
  scripts/zones/Chateau_dOraguille/npcs/Milchupain.lua
  scripts/zones/Chateau_dOraguille/npcs/Nachou.lua
  scripts/zones/Chateau_dOraguille/npcs/Perfaumand.lua
  scripts/zones/Chateau_dOraguille/npcs/Rahal.lua
  scripts/zones/Chateau_dOraguille/npcs/_6h0.lua
  scripts/zones/Chateau_dOraguille/npcs/_6h1.lua
  scripts/zones/Chateau_dOraguille/npcs/_6h4.lua
  scripts/zones/Northern_San_dOria/npcs/_6fc.lua
  scripts/zones/Southern_San_dOria/Zone.lua
Labels: reviewed

#1326 Update beast_roll.lua
  scripts/globals/effects/beast_roll.lua
Labels: reviewed

#1331 paying lip service: make trade-in dialog match traded item
  scripts/zones/Windurst_Woods/npcs/Tapoh_Lihzeh.lua
Labels: approved

#1344 Make BLM Trusts cast more conservatively
  scripts/globals/spells/trust/ajido-marujido.lua
  scripts/globals/spells/trust/shantotto.lua
  scripts/globals/spells/trust/shantotto_ii.lua
Labels: focus

#1341 Add step-down delays to Trust healing ticks
  src/map/ai/controllers/trust_controller.cpp
  src/map/ai/controllers/trust_controller.h
  src/map/entities/battleentity.cpp
  src/map/entities/battleentity.h
Labels: focus

#1334 Initial Dockerfile and docker-compose.yml
  DOCKER.md
  Dockerfile
  docker-compose.yml
  tools/wait_for_db_then_launch.sh
Labels: approved, reviewed

#1361 Switchstix: Fix issue with eating 10,000 pieces, refactor
  .gitignore
  scripts/zones/Castle_Zvahl_Baileys/npcs/Switchstix.lua
Labels: approved, reviewed

#1363 Make NM Lottery parameters configurable
  scripts/globals/mobs.lua
  scripts/globals/settings.lua
Labels: reviewed

#1319 Records of Eminence 3 - The Eminencing
  scripts/globals/caskets.lua
  scripts/globals/msg.lua
  scripts/globals/roe.lua
  scripts/globals/roe_records.lua
  sql/chars.sql
  src/common/mmo.h
  src/map/ai/controllers/player_controller.cpp
  src/map/entities/charentity.h
  src/map/entities/mobentity.cpp
  src/map/lua/luautils.cpp
  src/map/packet_system.cpp
  src/map/roe.cpp
  src/map/roe.h
  src/map/time_server.cpp
  src/map/utils/charutils.cpp
  src/map/vana_time.cpp
  src/map/vana_time.h
  tools/dbtool.py
  tools/migrations/char_timestamp.py
Labels: reviewed

#1365 Exploits List Part 1
  src/map/packet_system.cpp
  src/map/utils/synthutils.h
Labels: exploit

#1306 Completely replace all recipe data
  sql/synth_recipes.sql
Labels: approved

#1398 Adjust char timestamp migration for older Mariadb
  sql/chars.sql
  tools/migrations/char_timestamp.py
Labels: approved, reviewed

#1402 Fix determining relative entity positions, angles, and conal attacks
  scripts/globals/mobskills/dragon_breath.lua
  scripts/globals/mobskills/fiery_breath.lua
  scripts/globals/mobskills/geotic_breath.lua
  scripts/globals/mobskills/glacial_breath.lua
  scripts/globals/mobskills/sable_breath.lua
  scripts/globals/utils.lua
  src/common/utils.cpp
  src/common/utils.h
  src/map/ai/controllers/mob_controller.cpp
  src/map/ai/controllers/player_controller.cpp
  src/map/ai/helpers/pathfind.cpp
  src/map/ai/helpers/targetfind.cpp
  src/map/ai/states/range_state.cpp
  src/map/attack.cpp
  src/map/entities/charentity.cpp
  src/map/entities/mobentity.cpp
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/utils/attackutils.cpp
  src/map/utils/battleutils.cpp
Labels: approved, reviewed

#1415 Fix mobskill flag 0x010 (SKILLFLAG_REPLACE_ATTACK)
  src/map/mobskill.cpp
  src/map/mobskill.h
Labels: reviewed

#1430 Correct wyvern breath element selection
  scripts/globals/abilities/pets/flame_breath.lua
  scripts/globals/abilities/pets/gust_breath.lua
  scripts/globals/abilities/pets/healing_breath.lua
  scripts/globals/abilities/pets/healing_breath_ii.lua
  scripts/globals/abilities/pets/healing_breath_iii.lua
  scripts/globals/abilities/pets/healing_breath_iv.lua
  scripts/globals/abilities/pets/hydro_breath.lua
  scripts/globals/abilities/pets/lightning_breath.lua
  scripts/globals/abilities/pets/sand_breath.lua
  scripts/globals/pets/wyvern.lua
Labels: approved

#1434 Adds scripts for some Temporary Items
  scripts/globals/items/dusty_elixir.lua
  scripts/globals/items/tube_of_clear_salve_i.lua
  scripts/globals/items/tube_of_clear_salve_ii.lua
  scripts/globals/items/tube_of_healing_salve_i.lua
  scripts/globals/items/tube_of_healing_salve_ii.lua
  sql/item_usable.sql
Labels: reviewed
