Repository project-topaz/topaz, pull requests merged in 2020-07, with the labels that each got.

#754 Updates for item_equipment.sql, item_latents.sql, item_weapon.sql
  sql/item_equipment.sql
  sql/item_latents.sql
  sql/item_weapon.sql
Labels: reviewed

#778 Fix double-free errors in exit/crash
  src/common/taskmgr.cpp
  src/common/taskmgr.h
  src/map/lua/luautils.cpp
  src/map/map.cpp
  src/map/utils/battleutils.cpp
  src/map/utils/itemutils.cpp
  src/map/utils/zoneutils.cpp
  src/map/vana_time.cpp
  src/map/vana_time.h
Labels: approved

#791 Trust Melee Balancing
  scripts/globals/spells/trust/excenmille.lua
  scripts/globals/spells/trust/naji.lua
  scripts/globals/spells/trust/shantotto.lua
  src/map/utils/trustutils.cpp
Labels: merge ready

#794 Fix incorrect id in item_latents.sql; sort
  sql/item_latents.sql
Labels: approved, merge ready

#821 Fix Half Partition synth level requirements (Round 2)
  sql/synth_recipes.sql
Labels: approved

#797 removing spell script from sprinklers
  scripts/zones/RuAun_Gardens/mobs/Sprinkler.lua
  sql/mob_pools.sql
Labels: merge ready

#832 Fix issue with not referencing text IDs
  scripts/zones/Ship_bound_for_Selbina_Pirates/npcs/Bhagirath.lua
Labels: approved, merge ready

#841 Wrong resell price of apkal fletching
  sql/item_basic.sql
Labels: approved, merge ready

#744 Fix BRD song overwrite bug
  src/map/status_effect_container.cpp
Labels: merge ready

#755 Adjusted Switchstix Relic wait time to current retail
  scripts/zones/Castle_Zvahl_Baileys/npcs/Switchstix.lua
Labels: merge ready

#774 Full Speed Ahead: Various Improvements
  scripts/globals/effects/full_speed_ahead.lua
  scripts/globals/quests.lua
  scripts/quests/full_speed_ahead.lua
  scripts/zones/Batallia_Downs/Zone.lua
  scripts/zones/Upper_Jeuno/IDs.lua
  scripts/zones/Upper_Jeuno/npcs/Mapitoto.lua
Labels: merge ready

#779 Implement crafting skill limitation and various other fixes
  conf/default/map.conf
  src/map/map.cpp
  src/map/map.h
  src/map/utils/synthutils.cpp
Labels: merge ready

#786 tpz.zone referenced in casket_loot
  scripts/globals/casket_loot.lua
Labels: merge ready

#789 Flyers for Regine: Act III (Finale)
  scripts/quests/flyers_for_regine.lua
  scripts/zones/Northern_San_dOria/IDs.lua
  scripts/zones/Northern_San_dOria/Zone.lua
  scripts/zones/Northern_San_dOria/npcs/Boncort.lua
  scripts/zones/Northern_San_dOria/npcs/Capiria.lua
  scripts/zones/Northern_San_dOria/npcs/Coullene.lua
  scripts/zones/Northern_San_dOria/npcs/Guilberdrier.lua
  scripts/zones/Northern_San_dOria/npcs/Villion.lua
  scripts/zones/Port_San_dOria/IDs.lua
  scripts/zones/Port_San_dOria/Zone.lua
  scripts/zones/Port_San_dOria/npcs/Answald.lua
  scripts/zones/Port_San_dOria/npcs/Auvare.lua
  scripts/zones/Port_San_dOria/npcs/Miene.lua
  scripts/zones/Port_San_dOria/npcs/Portaure.lua
  scripts/zones/Port_San_dOria/npcs/Prietta.lua
  scripts/zones/Port_San_dOria/npcs/Regine.lua
  scripts/zones/Southern_San_dOria/IDs.lua
  scripts/zones/Southern_San_dOria/Zone.lua
  scripts/zones/Southern_San_dOria/npcs/Adaunel.lua
  scripts/zones/Southern_San_dOria/npcs/Blendare.lua
  scripts/zones/Southern_San_dOria/npcs/Leuveret.lua
  scripts/zones/Southern_San_dOria/npcs/Maugie.lua
  scripts/zones/Southern_San_dOria/npcs/Rosel.lua
Labels: merge ready

#804 ability ids and offsets
  scripts/globals/abilities/double-up.lua
  scripts/globals/ability.lua
  scripts/globals/msg.lua
  sql/abilities.sql
  src/map/ability.h
  src/map/ai/states/ability_state.cpp
  src/map/entities/charentity.cpp
  src/map/entities/petentity.cpp
  src/map/packet_system.cpp
  src/map/packets/char_abilities.cpp
Labels: merge ready

#790 Infill nm_spawn_points for all existing lottery mobs
  sql/nm_spawn_points.sql
Labels: merge ready

#807 Inquartata trait
  sql/traits.sql
  src/map/modifier.h
  src/map/utils/battleutils.cpp
Labels: merge ready

#811 Enhance !exec command
  scripts/commands/exec.lua
Labels: merge ready

#818 Change breaklinkshell for offline equipped members
  src/map/linkshell.cpp
  src/map/utils/charutils.cpp
Labels: merge ready

#842 Adding more rpi flags and updating cmake
  Makefile.am
  cmake/compiler.cmake
Labels: merge ready

#843 Alchemist torque
  scripts/globals/casket_loot.lua
Labels: merge ready

#809 Trust Balancing 2
  scripts/globals/spells/trust/excenmille.lua
  scripts/globals/spells/trust/naji.lua
  sql/mob_pools.sql
  src/map/ai/controllers/trust_controller.cpp
  src/map/utils/trustutils.cpp
Labels: merge ready

#836 make three pools for flesh eaters
  sql/mob_groups.sql
  sql/mob_pools.sql
Labels: merge ready

#844 Mob group/pool QC for beastmen in past vs present zones
  sql/mob_groups.sql
  sql/mob_pools.sql
Labels: merge ready

#799 Fix climbpix spawn conditions and THF AF2 script.
  scripts/zones/Sauromugue_Champaign/IDs.lua
  scripts/zones/Sauromugue_Champaign/Zone.lua
  scripts/zones/Sauromugue_Champaign/npcs/qm2.lua
  scripts/zones/Sauromugue_Champaign/npcs/qm3.lua
  scripts/zones/Sauromugue_Champaign/npcs/qm4.lua
  scripts/zones/Sauromugue_Champaign/npcs/qm5.lua
  scripts/zones/Sauromugue_Champaign/npcs/qm6.lua
  scripts/zones/Sauromugue_Champaign/npcs/qm7.lua
  scripts/zones/Windurst_Woods/npcs/Bopa_Greso.lua
  scripts/zones/Windurst_Woods/npcs/Cha_Lebagta.lua
  scripts/zones/Windurst_Woods/npcs/Nanaa_Mihgo.lua
Labels: approved

#810 Missing Divine_bijou drop in Dynamis Windurst
  sql/mob_droplist.sql
Labels: merge ready

#833 Trusts - Consider Trusts for Samba Dazes
  src/map/utils/battleutils.cpp
Labels: approved

#775 Trust Spawn/Despawn/Death/Teamwork & Error Messages
  scripts/globals/msg.lua
  scripts/globals/spells/trust/ajido-marujido.lua
  scripts/globals/spells/trust/ayame.lua
  scripts/globals/spells/trust/curilla.lua
  scripts/globals/spells/trust/excenmille.lua
  scripts/globals/spells/trust/iron_eater.lua
  scripts/globals/spells/trust/kupipi.lua
  scripts/globals/spells/trust/naji.lua
  scripts/globals/spells/trust/nanaa_mihgo.lua
  scripts/globals/spells/trust/shantotto.lua
  scripts/globals/spells/trust/trion.lua
  scripts/globals/spells/trust/volker.lua
  scripts/globals/trust.lua
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/packet_system.cpp
  src/map/packets/message_combat.cpp
  src/map/packets/message_combat.h
  src/map/party.cpp
  src/map/party.h
  src/map/utils/charutils.cpp
  win32/vcxproj/topaz_game.vcxproj
  win32/vcxproj/topaz_game.vcxproj.filters
Labels: approved

#796 I Can Hear a Rainbow: scripts/globals to scripts/quests
  scripts/globals/icanheararainbow.lua
  scripts/quests/i_can_hear_a_rainbow.lua
  scripts/zones/Batallia_Downs/Zone.lua
  scripts/zones/Beaucedine_Glacier/Zone.lua
  scripts/zones/Buburimu_Peninsula/Zone.lua
  scripts/zones/Cape_Teriggan/Zone.lua
  scripts/zones/East_Ronfaure/Zone.lua
  scripts/zones/East_Sarutabaruta/Zone.lua
  scripts/zones/Eastern_Altepa_Desert/Zone.lua
  scripts/zones/Jugner_Forest/Zone.lua
  scripts/zones/Konschtat_Highlands/Zone.lua
  scripts/zones/La_Theine_Plateau/Zone.lua
  scripts/zones/La_Theine_Plateau/npcs/qm3.lua
  scripts/zones/Meriphataud_Mountains/Zone.lua
  scripts/zones/North_Gustaberg/Zone.lua
  scripts/zones/Pashhow_Marshlands/Zone.lua
  scripts/zones/Rolanberry_Fields/Zone.lua
  scripts/zones/Sauromugue_Champaign/Zone.lua
  scripts/zones/South_Gustaberg/Zone.lua
  scripts/zones/Tahrongi_Canyon/Zone.lua
  scripts/zones/The_Sanctuary_of_ZiTah/Zone.lua
  scripts/zones/Valkurm_Dunes/Zone.lua
  scripts/zones/West_Ronfaure/Zone.lua
  scripts/zones/West_Sarutabaruta/Zone.lua
  scripts/zones/Western_Altepa_Desert/Zone.lua
  scripts/zones/Xarcabard/Zone.lua
  scripts/zones/Yhoator_Jungle/Zone.lua
  scripts/zones/Yuhtunga_Jungle/Zone.lua
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_zone.cpp
  src/map/lua/lua_zone.h
Labels: merge ready

#803 Guild shop always open
  scripts/globals/shop.lua
  scripts/zones/Bastok_Markets/npcs/Teerth.lua
  scripts/zones/Bastok_Mines/npcs/Odoba.lua
  scripts/zones/Metalworks/npcs/Vicious_Eye.lua
  scripts/zones/Mhaura/npcs/Celestina.lua
  scripts/zones/Mhaura/npcs/Mololo.lua
  scripts/zones/Northern_San_dOria/npcs/Cauzeriste.lua
  scripts/zones/Northern_San_dOria/npcs/Lucretia.lua
  scripts/zones/Selbina/npcs/Gibol.lua
  scripts/zones/Southern_San_dOria/npcs/Cletae.lua
  scripts/zones/Windurst_Waters/npcs/Chomo_Jinjahl.lua
  scripts/zones/Windurst_Woods/npcs/Meriri.lua
  scripts/zones/Windurst_Woods/npcs/Retto-Marutto.lua
  sql/guild_shops.sql
  src/map/lua/lua_baseentity.cpp
  src/map/packets/shop_items.cpp
  src/map/trade_container.cpp
  src/map/trade_container.h
Labels: merge ready

#820 Add database tool
  .gitignore
  migrations/README.md
  migrations/migrate.py
  sql/backups/.gitignore
  tools/Database_initial_setup.cmd
  tools/Database_update.cmd
  tools/README.md
  tools/dbtool.py
  tools/festive_moogle/README.md
  tools/festive_moogle/give_items.py
  tools/give_items.py
  tools/migrations/HP_masks_to_blobs.py
  tools/migrations/README.md
  tools/migrations/broken_linkshells.py
  tools/migrations/char_unlock_table_columns.py
  tools/migrations/cop_mission_ids.py
  tools/migrations/crystal_storage.py
  tools/migrations/mission_blob_extra.py
  tools/migrations/spell_blobs_to_spell_table.py
  tools/migrations/spell_family_column.py
  tools/migrations/unnamed_flags.py
  tools/migrations/utils.py
  tools/requirements.txt
Labels: merge ready

#876 Fix dbtool issues
  tools/dbtool.py
Labels: merge ready

#828 Puppetmaster NPC and Attachment Additions
  scripts/globals/abilities/pets/attachments/arcanic_cell.lua
  scripts/globals/abilities/pets/attachments/arcanic_cell_ii.lua
  scripts/globals/abilities/pets/attachments/arcanoclutch.lua
  scripts/globals/abilities/pets/attachments/arcanoclutch_ii.lua
  scripts/globals/abilities/pets/attachments/repeater.lua
  scripts/zones/Nashmau/npcs/Yoyoroon.lua
Labels: merge ready

#853 Trust Zone Flags
  scripts/globals/trust.lua
  sql/zone_settings.sql
  src/map/entities/charentity.cpp
  src/map/zone.h
Labels: merge ready

#860 *Added POS for GM !zone use
  scripts/zones/Heavens_Tower/Zone.lua
Labels: merge ready

#862 give ADD_EFFECT mobMod to Backoo
  scripts/zones/Buburimu_Peninsula/mobs/Backoo.lua
Labels: merge ready

#863 Job abilities enum-ed
  scripts/globals/ability.lua
  scripts/globals/items/allies_die.lua
  scripts/globals/items/avengers_die.lua
  scripts/globals/items/bard_die.lua
  scripts/globals/items/beastmaster_die.lua
  scripts/globals/items/black_mage_die.lua
  scripts/globals/items/blitzers_die.lua
  scripts/globals/items/blue_mage_die.lua
  scripts/globals/items/bolters_die.lua
  scripts/globals/items/casters_die.lua
  scripts/globals/items/companions_die.lua
  scripts/globals/items/corsair_die.lua
  scripts/globals/items/coursers_die.lua
  scripts/globals/items/dancer_die.lua
  scripts/globals/items/dark_knight_die.lua
  scripts/globals/items/dragoon_die.lua
  scripts/globals/items/geomancer_die.lua
  scripts/globals/items/misers_die.lua
  scripts/globals/items/monk_die.lua
  scripts/globals/items/ninja_die.lua
  scripts/globals/items/paladin_die.lua
  scripts/globals/items/puppetmaster_die.lua
  scripts/globals/items/ranger_die.lua
  scripts/globals/items/red_mage_die.lua
  scripts/globals/items/rune_fencer_die.lua
  scripts/globals/items/samurai_die.lua
  scripts/globals/items/scholar_die.lua
  scripts/globals/items/summoner_die.lua
  scripts/globals/items/tacticians_die.lua
  scripts/globals/items/thief_die.lua
  scripts/globals/items/warrior_die.lua
  scripts/globals/items/white_mage_die.lua
  src/map/ability.h
Labels: merge ready

#868 Item QC
  sql/item_basic.sql
  sql/item_equipment.sql
Labels: merge ready

#874 npcUtilify Zeni NM pops
  scripts/zones/Alzadaal_Undersea_Ruins/npcs/qm1.lua
  scripts/zones/Alzadaal_Undersea_Ruins/npcs/qm2.lua
  scripts/zones/Alzadaal_Undersea_Ruins/npcs/qm3.lua
  scripts/zones/Alzadaal_Undersea_Ruins/npcs/qm4.lua
  scripts/zones/Arrapago_Reef/npcs/qm1.lua
  scripts/zones/Arrapago_Reef/npcs/qm2.lua
  scripts/zones/Arrapago_Reef/npcs/qm3.lua
  scripts/zones/Arrapago_Reef/npcs/qm4.lua
  scripts/zones/Aydeewa_Subterrane/npcs/qm1.lua
  scripts/zones/Aydeewa_Subterrane/npcs/qm2.lua
  scripts/zones/Aydeewa_Subterrane/npcs/qm3.lua
  scripts/zones/Bhaflau_Thickets/npcs/qm1.lua
  scripts/zones/Bhaflau_Thickets/npcs/qm2.lua
  scripts/zones/Caedarva_Mire/npcs/qm1.lua
  scripts/zones/Caedarva_Mire/npcs/qm2.lua
  scripts/zones/Caedarva_Mire/npcs/qm3.lua
  scripts/zones/Caedarva_Mire/npcs/qm4.lua
  scripts/zones/Halvung/npcs/qm2.lua
  scripts/zones/Halvung/npcs/qm3.lua
  scripts/zones/Halvung/npcs/qm4.lua
  scripts/zones/Mamook/npcs/qm1.lua
  scripts/zones/Mamook/npcs/qm2.lua
  scripts/zones/Wajaom_Woodlands/npcs/qm1.lua
  scripts/zones/Wajaom_Woodlands/npcs/qm2.lua
  scripts/zones/Wajaom_Woodlands/npcs/qm3.lua
  scripts/zones/Wajaom_Woodlands/npcs/qm4.lua
Labels: merge ready

#890 Fix typo in linkshell slot
  src/map/utils/charutils.cpp
Labels: approved, merge ready

#877 Trust Stability
  scripts/globals/spells/tractor.lua
  scripts/globals/spells/warp_ii.lua
  scripts/globals/trust.lua
  src/map/ai/controllers/trust_controller.cpp
  src/map/battlefield.cpp
  src/map/entities/charentity.cpp
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/zone_entities.cpp
Labels: focus, help wanted, merge ready

#892 Trust Targetting
  src/map/ai/helpers/targetfind.cpp
  src/map/entities/trustentity.cpp
Labels: merge ready

#578 Trust animations
  sql/mob_pools.sql
  sql/mob_skill_lists.sql
  sql/mob_skills.sql
Labels: merge ready

#879 Halvung LUA cleanup
  scripts/zones/Halvung/Zone.lua
  scripts/zones/Halvung/mobs/Farlarder_the_Shrewd.lua
  scripts/zones/Halvung/mobs/Gurfurlur_the_Menacing.lua
  scripts/zones/Halvung/mobs/Kirlirger_the_Abhorrent.lua
  scripts/zones/Halvung/mobs/Wamouracampa.lua
  scripts/zones/Halvung/mobs/Wheel_Wamoura.lua
  scripts/zones/Halvung/npcs/Mining_Point.lua
  scripts/zones/Halvung/npcs/Survival_Guide.lua
  scripts/zones/Halvung/npcs/qm1.lua
Labels: approved, merge ready

#889 LUA cleanup: Hall of Transference, Hall of the Gods
  scripts/zones/Hall_of_Transference/Zone.lua
  scripts/zones/Hall_of_Transference/npcs/_0e0.lua
  scripts/zones/Hall_of_Transference/npcs/_0e1.lua
  scripts/zones/Hall_of_Transference/npcs/_0e2.lua
  scripts/zones/Hall_of_Transference/npcs/_0e3.lua
  scripts/zones/Hall_of_Transference/npcs/_0e4.lua
  scripts/zones/Hall_of_Transference/npcs/_0e5.lua
  scripts/zones/Hall_of_Transference/npcs/_0e6.lua
  scripts/zones/Hall_of_Transference/npcs/_0e7.lua
  scripts/zones/Hall_of_Transference/npcs/_0e8.lua
  scripts/zones/Hall_of_the_Gods/Zone.lua
  scripts/zones/Hall_of_the_Gods/npcs/Shimmering_Circle.lua
  scripts/zones/Hall_of_the_Gods/npcs/_6z0.lua
Labels: approved, merge ready

#905 Stops steelshells in boyahda from linking
  sql/mob_pools.sql
Labels: approved, merge ready

#908 Allow players to pop Windurst 8-2 mission NMs aggro-less with sneak
  scripts/zones/Outer_Horutoto_Ruins/npcs/_5e5.lua
Labels: merge ready

#906 Fixes status_effect flags for various consumes-effect-on-hit buffs
  sql/status_effects.sql
Labels: merge ready

#900 Remove trailing whitespace in scripts
  scripts/globals/items/rolanberry_daifuku.lua
  scripts/globals/items/shivas_claws.lua
  scripts/globals/spell_data.lua
  scripts/mixins/spawn_casket.lua
  scripts/zones/Apollyon/Zone.lua
  scripts/zones/Apollyon/npcs/Radiant_Aureole.lua
  scripts/zones/Balgas_Dais/mobs/Bitoso.lua
  scripts/zones/Bastok_Mines/npcs/Parraggoh.lua
  scripts/zones/Buburimu_Peninsula/IDs.lua
  scripts/zones/Buburimu_Peninsula/Zone.lua
  scripts/zones/Chamber_of_Oracles/mobs/Blizzard_Wyvern.lua
  scripts/zones/Chamber_of_Oracles/npcs/Armoury_Crate.lua
  scripts/zones/Gusgen_Mines/npcs/qm1.lua
  scripts/zones/King_Ranperres_Tomb/mobs/Corrupted_Ulbrig.lua
  scripts/zones/Mamook/mobs/Mikilulu.lua
  scripts/zones/Mamook/mobs/Poroggo_Casanova.lua
  scripts/zones/Mamook/npcs/Toads_Footprint1.lua
  scripts/zones/Maze_of_Shakhrami/npcs/qm1.lua
  scripts/zones/Metalworks/npcs/Alois.lua
  scripts/zones/Ordelles_Caves/npcs/qm1.lua
  scripts/zones/Port_Windurst/npcs/Kohlo-Lakolo.lua
  scripts/zones/Rabao/npcs/Leodarion.lua
  scripts/zones/RuLude_Gardens/npcs/Magian_Moogle_Orange.lua
  scripts/zones/Temenos/npcs/Matter_Diffusion_Module.lua
  scripts/zones/The_Garden_of_RuHmet/Zone.lua
  scripts/zones/West_Ronfaure/npcs/Vilatroire.lua
Labels: merge ready

#910 Fix issues with Lion II cipher and some cutscenes
  scripts/zones/Konschtat_Highlands/npcs/Shattered_Telepoint.lua
  scripts/zones/La_Theine_Plateau/npcs/Shattered_Telepoint.lua
  scripts/zones/Tahrongi_Canyon/npcs/Shattered_Telepoint.lua
  scripts/zones/Windurst_Walls/Zone.lua
Labels: merge ready

#784 Extensions to the Lua system + Correct Item Code for Magian Trials
  src/map/items/item_equipment.cpp
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/lua/lua_item.cpp
  src/map/lua/lua_item.h
  src/map/lua/luautils.cpp
  src/map/lua/luautils.h
  src/map/utils/itemutils.cpp
  src/map/utils/itemutils.h
Labels: approved

#857 [Bard] Fix TP loss on instrument swap
  src/map/utils/charutils.cpp
Labels: approved
