Repository project-topaz/topaz, pull requests merged in 2020-11, with the labels that each got.

#1461 Fix Bind not breaking when it should
  scripts/globals/abilities/devotion.lua
  scripts/globals/abilities/martyr.lua
  scripts/globals/weaponskills.lua
  src/map/lua/lua_baseentity.cpp
  src/map/status_effect_container.cpp
  src/map/utils/battleutils.cpp
Labels: exploit

#1463 Resolve BLU spell setting exploits
  src/map/packet_system.cpp
  src/map/utils/blueutils.cpp
Labels: exploit

#1476 CoP 5-1 Player obtains Mysterious Amulet and Light of Vahzl
  scripts/zones/AlTaieu/Zone.lua
  scripts/zones/Beaucedine_Glacier/Zone.lua
  scripts/zones/Promyvion-Vahzl/IDs.lua
  scripts/zones/Promyvion-Vahzl/Zone.lua
  scripts/zones/PsoXja/npcs/_i99.lua
Labels: reviewed

#1480 Fixes Gobbie Mystery Box "You must wait another 0 days..."
  scripts/globals/gobbiemysterybox.lua
Labels: reviewed

#1465 Implements the Retrace spell and related usable items
  scripts/globals/effects/teleport.lua
  scripts/globals/items/cobra_staff.lua
  scripts/globals/items/fourth_staff.lua
  scripts/globals/items/ram_staff.lua
  scripts/globals/items/scroll_of_instant_retrace.lua
  scripts/globals/spells/retrace.lua
  scripts/globals/teleports.lua
  scripts/globals/zone.lua
  sql/item_usable.sql
  sql/spell_list.sql
Labels: reviewed

#1413 Adjust Trust and Mount flags in Adoulin and ToAU zones
  sql/zone_settings.sql
Labels: reviewed

#1447 Desynths
  sql/synth_recipes.sql
Labels: crafting, reviewed

#1497 Add new chat channels to the enums
  scripts/globals/msg.lua
  src/map/packets/chat_message.h
Labels: reviewed

#1407 General combat calculation improvements for Avatars
  scripts/globals/summon.lua
  src/map/attack.cpp
  src/map/utils/battleutils.cpp
  src/map/utils/battleutils.h
  src/map/utils/petutils.cpp
Labels: reviewed

#1504 Add Lua Hook for character's lastOnline timestamp
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
Labels: reviewed

#1503 Fix BST Ready timer does not accumulate charges after Call Beast.
  scripts/globals/abilities/call_beast.lua
Labels: reviewed

#1508 Block attempts to Ranged Attack from incorrect states
  src/map/packet_system.cpp
Labels: exploit

#1501 adds missing currencies to show inside currency1 menu
  sql/char_points.sql
  src/map/packets/currency1.cpp
  tools/dbtool.py
  tools/migrations/currency_columns.py
Labels: reviewed

#1516 Resolve guild trade-in exploit
  src/map/guild.cpp
Labels: exploit

#1518 Resolve Moghouse zoneline warping exploit
  src/map/packet_system.cpp
Labels: exploit

#1429 Fix cutscene in COP 2-5 "Ancient Vows"
  scripts/zones/Misareaux_Coast/npcs/Spatial_Displacement.lua
  scripts/zones/Misareaux_Coast/npcs/_0p2.lua
  scripts/zones/Riverne-Site_A01/Zone.lua
  scripts/zones/Tavnazian_Safehold/npcs/Despachiaire.lua
  scripts/zones/Tavnazian_Safehold/npcs/Justinius.lua
Labels: reviewed

#1360 Align respawn timer for normal dungeon mobs:
  sql/mob_groups.sql
Labels: hold

#1343 [WIP] The craftening, part 4. More skill up changes.
  conf/default/map.conf
  src/map/map.cpp
  src/map/map.h
  src/map/utils/synthutils.cpp
Labels: crafting

#957 PR: DRG mobs now spawn wyverns when they idle
  src/map/utils/mobutils.cpp
Labels: help wanted, research needed

#1370 Fix non conforming naming of settings and adjust styling in related scripts
  scripts/globals/mobs.lua
  scripts/globals/settings.lua
  scripts/zones/Crawlers_Nest/globals.lua
  scripts/zones/Crawlers_Nest/npcs/qm10.lua
  scripts/zones/Crawlers_Nest/npcs/qm11.lua
  scripts/zones/Crawlers_Nest/npcs/qm12.lua
  scripts/zones/Garlaige_Citadel/globals.lua
  scripts/zones/Garlaige_Citadel/npcs/qm18.lua
  scripts/zones/Garlaige_Citadel/npcs/qm19.lua
  scripts/zones/Garlaige_Citadel/npcs/qm20.lua
  scripts/zones/The_Eldieme_Necropolis/globals.lua
  scripts/zones/Xarcabard/mobs/Boreal_Coeurl.lua
  scripts/zones/Xarcabard/mobs/Boreal_Hound.lua
  scripts/zones/Xarcabard/mobs/Boreal_Tiger.lua
  scripts/zones/Xarcabard/npcs/qm2.lua
  scripts/zones/Xarcabard/npcs/qm3.lua
  scripts/zones/Xarcabard/npcs/qm4.lua
Labels: reviewed

#953 Adds Kyoshu Kyahan latent effects and new item latent mod
  scripts/globals/status.lua
  sql/item_latents.sql
  src/map/latent_effect.cpp
  src/map/latent_effect.h
  src/map/latent_effect_container.cpp
  src/map/latent_effect_container.h
Labels: hold

#723 Geomancer abilities, merits, and adjustments
  scripts/globals/abilities/blaze_of_glory.lua
  scripts/globals/abilities/bolster.lua
  scripts/globals/abilities/concentric_pulse.lua
  scripts/globals/abilities/dematerialize.lua
  scripts/globals/abilities/ecliptic_attrition.lua
  scripts/globals/abilities/entrust.lua
  scripts/globals/abilities/full_circle.lua
  scripts/globals/abilities/lasting_emanation.lua
  scripts/globals/abilities/life_cycle.lua
  scripts/globals/abilities/mending_halation.lua
  scripts/globals/abilities/pets/concentric_pulse.lua
  scripts/globals/abilities/pets/mending_halation.lua
  scripts/globals/abilities/pets/radial_arcana.lua
  scripts/globals/abilities/radial_arcana.lua
  scripts/globals/abilities/theurgic_focus.lua
  scripts/globals/abilities/widened_compass.lua
  scripts/globals/ability.lua
  scripts/globals/effects/blaze_of_glory.lua
  scripts/globals/effects/bolster.lua
  scripts/globals/effects/ecliptic_attrition.lua
  scripts/globals/effects/lasting_emanation.lua
  scripts/globals/effects/regen_ii.lua
  scripts/globals/effects/theurgic_focus.lua
  scripts/globals/effects/widened_compass.lua
  scripts/globals/magic.lua
  scripts/globals/pets/luopan.lua
  scripts/globals/status.lua
  sql/spell_list.sql
  src/map/ai/states/magic_state.cpp
  src/map/entities/battleentity.h
  src/map/entities/charentity.cpp
  src/map/entities/luopanentity.cpp
  src/map/entities/luopanentity.h
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/merit.cpp
  src/map/packets/action.cpp
  src/map/spell.cpp
  src/map/spell.h
  src/map/status_effect_container.cpp
  src/map/utils/battleutils.cpp
  src/map/utils/petutils.cpp
Labels: hold

#1477 Created setallskills.lua
  scripts/commands/setallskills.lua
Labels: reviewed

#751 Added Scholar AF quest Seeing Blood-Red
  scripts/zones/Grauberg_[S]/npcs/34.lua
  scripts/zones/Pashhow_Marshlands_[S]/npcs/Indescript_Markings.lua
  scripts/zones/The_Eldieme_Necropolis_[S]/npcs/Erlene.lua
Labels: WIP, help wanted

#685 Abyssea Lights system
  scripts/commands/addlights.lua
  scripts/commands/resetlights.lua
  scripts/globals/abyssea.lua
  scripts/globals/effects/healing.lua
  scripts/globals/effects/visitant.lua
  scripts/globals/moblights.lua
  scripts/globals/settings.lua
  scripts/mixins/drop_lights.lua
  scripts/mixins/zones/Abyssea-Altepa.lua
  scripts/mixins/zones/Abyssea-Attohwa.lua
  scripts/mixins/zones/Abyssea-Grauberg.lua
  scripts/mixins/zones/Abyssea-Konschtat.lua
  scripts/mixins/zones/Abyssea-La_Theine.lua
  scripts/mixins/zones/Abyssea-Misareaux.lua
  scripts/mixins/zones/Abyssea-Tahrongi.lua
  scripts/mixins/zones/Abyssea-Uleguerand.lua
  scripts/mixins/zones/Abyssea-Vunkerl.lua
  scripts/zones/Abyssea-Altepa/IDs.lua
  scripts/zones/Abyssea-Altepa/Zone.lua
  scripts/zones/Abyssea-Attohwa/IDs.lua
  scripts/zones/Abyssea-Attohwa/Zone.lua
  scripts/zones/Abyssea-Empyreal_Paradox/IDs.lua
  scripts/zones/Abyssea-Empyreal_Paradox/Zone.lua
  scripts/zones/Abyssea-Grauberg/IDs.lua
  scripts/zones/Abyssea-Grauberg/Zone.lua
  scripts/zones/Abyssea-Konschtat/IDs.lua
  scripts/zones/Abyssea-Konschtat/Zone.lua
  scripts/zones/Abyssea-La_Theine/IDs.lua
  scripts/zones/Abyssea-La_Theine/Zone.lua
  scripts/zones/Abyssea-Misareaux/IDs.lua
  scripts/zones/Abyssea-Misareaux/Zone.lua
  scripts/zones/Abyssea-Tahrongi/IDs.lua
  scripts/zones/Abyssea-Tahrongi/Zone.lua
  scripts/zones/Abyssea-Uleguerand/IDs.lua
  scripts/zones/Abyssea-Uleguerand/Zone.lua
  scripts/zones/Abyssea-Vunkerl/IDs.lua
  scripts/zones/Abyssea-Vunkerl/Zone.lua
  sql/status_effects.sql
Labels: hold

#943 Increases range of all spells from 20.4y to 21.5y as confirmed by tes…
  sql/spell_list.sql
Labels: research needed
