Repository project-topaz/topaz, pull requests merged in 2020-06, with the labels that each got.

#621 Fix game + connect servers hangs or crashes on Exit / Ctrl-C / SIGINT
  src/common/zmq.hpp
  src/login/login.cpp
  src/login/message_server.cpp
  src/login/message_server.h
  src/map/message.h
Labels: merge ready

#674 Add Missing Shuriken Pouches
  scripts/globals/items/fuma_shuriken_pouch.lua
  scripts/globals/items/juji_shuriken_pouch.lua
  scripts/globals/items/manji_shuriken_pouch.lua
  scripts/globals/items/shuriken_pouch.lua
  sql/item_usable.sql
Labels: reviewed

#668 fix GetNPCByID not returning instanced NPCs
  src/map/lua/luautils.cpp
Labels: reviewed

#661 Traits Update
  sql/traits.sql
Labels: reviewed

#665 Fix Trusts drawn in crashing the map server.
  src/map/lua/luautils.cpp
Labels: reviewed

#652 Working Curio Vendor Moogle
  scripts/globals/shop.lua
  scripts/zones/Port_Bastok/npcs/Curio_Vendor_Moogle.lua
  scripts/zones/Port_San_dOria/npcs/Curio_Vendor_Moogle.lua
  scripts/zones/Port_Windurst/npcs/Curio_Vendor_Moogle.lua
Labels: reviewed

#678 Change updateClaim to clear claim when no args
  src/map/lua/lua_baseentity.cpp
Labels: reviewed

#682 Fix server crashes during quest "Flyers for Regine"
  scripts/globals/npc_util.lua
  scripts/zones/Northern_San_dOria/IDs.lua
  scripts/zones/Northern_San_dOria/npcs/Boncort.lua
  scripts/zones/Northern_San_dOria/npcs/Capiria.lua
  scripts/zones/Northern_San_dOria/npcs/Coullene.lua
  scripts/zones/Northern_San_dOria/npcs/Guilberdrier.lua
  scripts/zones/Northern_San_dOria/npcs/Villion.lua
  scripts/zones/Port_San_dOria/IDs.lua
  scripts/zones/Port_San_dOria/npcs/Answald.lua
  scripts/zones/Port_San_dOria/npcs/Auvare.lua
  scripts/zones/Port_San_dOria/npcs/Miene.lua
  scripts/zones/Port_San_dOria/npcs/Portaure.lua
  scripts/zones/Port_San_dOria/npcs/Prietta.lua
  scripts/zones/Southern_San_dOria/IDs.lua
  scripts/zones/Southern_San_dOria/npcs/Adaunel.lua
  scripts/zones/Southern_San_dOria/npcs/Blendare.lua
  scripts/zones/Southern_San_dOria/npcs/Leuveret.lua
  scripts/zones/Southern_San_dOria/npcs/Maugie.lua
  scripts/zones/Southern_San_dOria/npcs/Rosel.lua
Labels: reviewed

#657 Updating database tooling
  tools/Database_initial_setup.cmd
  tools/Database_update.cmd
Labels: reviewed

#684 Changed Shield Bash for Paladin UPDATE: 12FEB2020
  scripts/globals/abilities/shield_bash.lua
  sql/abilities.sql
  sql/merits.sql
Labels: merge ready

#683 Implement Rampart as -25% SDT rather than 100% magic shield
  scripts/globals/abilities/rampart.lua
  scripts/globals/effects/rampart.lua
  scripts/globals/status.lua
  sql/status_effects.sql
  src/map/status_effect.h
Labels: reviewed

#666 Rov valor buffs
  scripts/globals/regimes.lua
Labels: reviewed

#647 Trust JAs and pre-WS work
  scripts/globals/abilities/despoil.lua
  scripts/globals/effects/battlefield.lua
  scripts/globals/effects/confrontation.lua
  scripts/globals/effects/level_restriction.lua
  scripts/globals/effects/level_sync.lua
  scripts/globals/gambits.lua
  scripts/globals/spells/trust/ajido-marujido.lua
  scripts/globals/spells/trust/ayame.lua
  scripts/globals/spells/trust/curilla.lua
  scripts/globals/spells/trust/excenmille.lua
  scripts/globals/spells/trust/iron_eater.lua
  scripts/globals/spells/trust/kupipi.lua
  scripts/globals/spells/trust/naji.lua
  scripts/globals/spells/trust/nanaa_mihgo.lua
  scripts/globals/spells/trust/shantotto.lua
  scripts/globals/spells/trust/trion.lua
  scripts/globals/spells/trust/volker.lua
  scripts/globals/weaponskills.lua
  src/map/ai/controllers/trust_controller.cpp
  src/map/ai/controllers/trust_controller.h
  src/map/ai/helpers/gambits_container.cpp
  src/map/ai/helpers/gambits_container.h
  src/map/entities/trustentity.cpp
  src/map/entities/trustentity.h
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/lua/luautils.cpp
  src/map/lua/luautils.h
  src/map/mob_spell_container.cpp
  src/map/utils/battleutils.cpp
  src/map/utils/trustutils.cpp
Labels: review ready, reviewed

#692 Trust JA Fix (Naji provokes himself)
  src/map/ai/helpers/gambits_container.cpp
Labels: merge ready

#693 Trust Engage Condition Fix
  src/map/ai/controllers/player_controller.cpp
  src/map/ai/controllers/player_controller.h
  src/map/ai/controllers/trust_controller.cpp
Labels: merge ready

#680 Update Despot
  scripts/zones/RuAun_Gardens/mobs/Despot.lua
  scripts/zones/RuAun_Gardens/mobs/Groundskeeper.lua
Labels: reviewed

#704 Gobbiebag uses tpz.inv and does the correct bags
  scripts/zones/Lower_Jeuno/npcs/Bluffnix.lua
Labels: merge ready

#717 Trust fixes for -Werror
  src/map/entities/trustentity.cpp
  src/map/lua/luautils.cpp
  src/map/party.cpp
  src/map/status_effect_container.cpp
  src/map/utils/trustutils.cpp
  src/map/zone_entities.cpp
Labels: approved

#706 Fix Flashbulb and mob Sleepga from crashing server when resisted
  scripts/globals/abilities/pets/flashbulb.lua
  scripts/globals/abilities/pets/sleepga.lua
Labels: approved

#662 Fixes crystal drops for parties.
  src/map/entities/mobentity.cpp
  src/map/utils/charutils.cpp
Labels: approved

#705 Fix unable to continue RoV questline
  scripts/zones/Konschtat_Highlands/npcs/Shattered_Telepoint.lua
  scripts/zones/La_Theine_Plateau/npcs/Shattered_Telepoint.lua
  scripts/zones/Tahrongi_Canyon/npcs/Shattered_Telepoint.lua
Labels: approved

#708 Custom epoch for Vana'diel time
  conf/default/map.conf
  src/map/lua/luautils.cpp
  src/map/map.cpp
  src/map/map.h
  src/map/vana_time.cpp
  src/map/vana_time.h
Labels: merge ready

#718 Table spell IDs + move other magic enums out of magic global
  scripts/globals/magic.lua
  scripts/globals/spell_data.lua
Labels: approved

#703 IP/Subnet mask in socket was calculated incorrectly
  src/common/socket.cpp
Labels: approved

#719 Updates for nix builds
  Makefile.am
  cmake/compiler.cmake
  src/common/utils.cpp
  src/map/ai/controllers/automaton_controller.cpp
  src/map/entities/charentity.cpp
  src/map/packet_system.cpp
Labels: approved

#742 fixing merit values based on 1000 tp model and fixing overflow
  sql/merits.sql
  src/map/merit.cpp
Labels: focus, merge ready

#699 Add geomancer -ra spells and scrolls
  scripts/globals/items/scroll_of_aera.lua
  scripts/globals/items/scroll_of_aera_ii.lua
  scripts/globals/items/scroll_of_blizzara.lua
  scripts/globals/items/scroll_of_blizzara_ii.lua
  scripts/globals/items/scroll_of_fira.lua
  scripts/globals/items/scroll_of_fira_ii.lua
  scripts/globals/items/scroll_of_stonera.lua
  scripts/globals/items/scroll_of_stonera_ii.lua
  scripts/globals/items/scroll_of_thundara.lua
  scripts/globals/items/scroll_of_thundara_ii.lua
  scripts/globals/items/scroll_of_watera.lua
  scripts/globals/items/scroll_of_watera_ii.lua
  scripts/globals/spells/aera.lua
  scripts/globals/spells/aera_ii.lua
  scripts/globals/spells/blizzara.lua
  scripts/globals/spells/blizzara_ii.lua
  scripts/globals/spells/fira.lua
  scripts/globals/spells/fira_ii.lua
  scripts/globals/spells/stonera.lua
  scripts/globals/spells/stonera_ii.lua
  scripts/globals/spells/thundara.lua
  scripts/globals/spells/thundara_ii.lua
  scripts/globals/spells/watera.lua
  scripts/globals/spells/watera_ii.lua
  sql/item_basic.sql
  sql/item_usable.sql
Labels: reviewed

#725 Double-up cooldown adjustments
  scripts/globals/ability.lua
  sql/abilities.sql
Labels: approved

#737 Adds Rising Sun and Ebony Wand desynths
  sql/synth_recipes.sql
Labels: approved, merge ready

#761 Add adds to Promy-Dem BCMN
  sql/bcnm_battlefield.sql
Labels: merge ready

#759 Fix region check when OP teleporting
  scripts/globals/conquest.lua
Labels: approved

#747 Changes to two mob droplist
  sql/mob_droplist.sql
Labels: approved

#752 Herc mods
  sql/item_mods.sql
Labels: approved

#756 Remove automatic multipliers when mob is marked as an NM
  src/map/utils/mobutils.cpp
Labels: merge ready

#746 Updated Binary to let RUN use their innate spells
  sql/spell_list.sql
Labels: approved

#731 Adjust NPC script for Sandy 6-2 "Ranperre's Final Rest"
  scripts/zones/Chateau_dOraguille/npcs/Perfaumand.lua
  scripts/zones/Chateau_dOraguille/npcs/_6h0.lua
  scripts/zones/King_Ranperres_Tomb/mobs/Corrupted_Soffeil.lua
  scripts/zones/King_Ranperres_Tomb/mobs/Corrupted_Ulbrig.lua
  scripts/zones/King_Ranperres_Tomb/mobs/Corrupted_Yorgos.lua
  scripts/zones/King_Ranperres_Tomb/npcs/Tombstone.lua
  scripts/zones/King_Ranperres_Tomb/npcs/_5a0.lua
  scripts/zones/Northern_San_dOria/npcs/Grilau.lua
  scripts/zones/Southern_San_dOria/npcs/Ambrotien.lua
  scripts/zones/Southern_San_dOria/npcs/Endracion.lua
Labels: approved

#722 Add var and binding for isDualWielding + remove presumptuous granting of mod to all NIN NMs
  scripts/globals/weaponskills.lua
  src/map/attackround.cpp
  src/map/entities/battleentity.cpp
  src/map/entities/battleentity.h
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/utils/charutils.cpp
  src/map/utils/mobutils.cpp
Labels: approved

#772 BaseSell prices and version.conf message updates.
  conf/default/version.conf
  sql/item_basic.sql
Labels: approved

#770 Full Speed Ahead completion check
  scripts/zones/Upper_Jeuno/npcs/Mapitoto.lua
Labels: approved
