Repository project-topaz/topaz, pull requests merged in 2020-03, with the labels that each got.

#396 change the query to grab right data
  src/map/instance_loader.cpp
Labels: bug, review ready

#358 Move battlefield capacity check to correct place.
  scripts/globals/bcnm.lua
Labels: merge ready

#362 [WIP] Rhapsodies of Vana'diel 1-1 to 1-18
  scripts/globals/missions.lua
  scripts/globals/mobskills/bonebreaking_barrage.lua
  scripts/globals/mobskills/calcifying_claw.lua
  scripts/globals/mobskills/clarsach_call.lua
  scripts/globals/mobskills/divesting_stampede.lua
  scripts/globals/mobskills/entice.lua
  scripts/globals/mobskills/hellfire_arrow.lua
  scripts/globals/mobskills/hysteric_assault.lua
  scripts/globals/mobskills/incensed_pummel.lua
  scripts/globals/mobskills/lunatic_voice.lua
  scripts/globals/mobskills/sonic_buffet.lua
  scripts/globals/mobskills/soulshattering_roar.lua
  scripts/globals/rhapsodies.lua
  scripts/globals/status.lua
  scripts/zones/Bastok_Markets/Zone.lua
  scripts/zones/Bastok_Mines/Zone.lua
  scripts/zones/Escha_ZiTah/Zone.lua
  scripts/zones/Konschtat_Highlands/npcs/Shattered_Telepoint.lua
  scripts/zones/La_Theine_Plateau/npcs/Shattered_Telepoint.lua
  scripts/zones/Mhaura/Zone.lua
  scripts/zones/Mhaura/npcs/Ekokoko.lua
  scripts/zones/Mhaura/npcs/Numi_Adaligo.lua
  scripts/zones/Mhaura/npcs/Tonasav.lua
  scripts/zones/Mhaura/npcs/Vera.lua
  scripts/zones/Norg/npcs/_700.lua
  scripts/zones/Northern_San_dOria/Zone.lua
  scripts/zones/Port_Bastok/Zone.lua
  scripts/zones/Port_San_dOria/Zone.lua
  scripts/zones/Port_Windurst/Zone.lua
  scripts/zones/Qufim_Island/IDs.lua
  scripts/zones/Qufim_Island/mobs/Ophiotaurus.lua
  scripts/zones/Qufim_Island/npcs/Undulating_Confluence.lua
  scripts/zones/Sea_Serpent_Grotto/npcs/qm7.lua
  scripts/zones/Selbina/Zone.lua
  scripts/zones/Selbina/npcs/Abelard.lua
  scripts/zones/Selbina/npcs/Isacio.lua
  scripts/zones/Selbina/npcs/Naillina.lua
  scripts/zones/Selbina/npcs/Pacomart.lua
  scripts/zones/Southern_San_dOria/Zone.lua
  scripts/zones/Tahrongi_Canyon/npcs/Shattered_Telepoint.lua
  scripts/zones/Windurst_Walls/Zone.lua
  scripts/zones/Windurst_Waters/Zone.lua
  scripts/zones/Windurst_Woods/Zone.lua
  scripts/zones/Yuhtunga_Jungle/IDs.lua
  scripts/zones/Yuhtunga_Jungle/mobs/Siren.lua
  scripts/zones/Yuhtunga_Jungle/npcs/qm11.lua
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/utils/charutils.cpp
Labels: WIP

#394 Default Confs now in subfolder. No more accidentally sending your password
  .gitignore
  conf/default/login.conf
  conf/default/maint.conf
  conf/default/map.conf
  conf/default/packet_tcp.conf
  conf/default/packet_udp.conf
  conf/default/search_server.conf
  conf/default/server_message.conf
  conf/default/server_message_fr.conf
  conf/readme.md
Labels: merge ready

#398 only players currently on Dark Spark quest will get credit for the kill
  scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua
  scripts/zones/Castle_Zvahl_Baileys/npcs/Torch.lua
Labels: merge ready

#421 Correct drop IDs for Padfoot, comment drops in mob_droplist.sql Fixes #420
  scripts/zones/Lufaise_Meadows/mobs/Padfoot.lua
  sql/mob_droplist.sql
Labels: merge ready

#414 Add ability sql for Bestial Loyalty
  sql/abilities.sql
Labels: merge ready

#416 Fix Chasing Quotas (DRG AF2) timing
  scripts/zones/Port_San_dOria/npcs/Ceraulian.lua
Labels: merge ready

#405 Gobbie Mystery Box plumbing
  conf/map.conf
  migrations/add_daily_tally_column.py
  migrations/add_timecreated_column.py
  migrations/migrate.py
  scripts/globals/settings.lua
  scripts/zones/Windurst_Walls/IDs.lua
  scripts/zones/Windurst_Walls/npcs/Arbitrix.lua
  sql/char_points.sql
  sql/chars.sql
  src/map/daily_system.cpp
  src/map/daily_system.h
  src/map/entities/charentity.cpp
  src/map/entities/charentity.h
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/map.cpp
  src/map/map.h
  src/map/time_server.cpp
  win32/vcxproj/topaz_game.vcxproj
  win32/vcxproj/topaz_game.vcxproj.filters
Labels: focus, reviewed

#415 Fix Beast Affinity merit bonus application
  src/map/utils/petutils.cpp
Labels: merge ready

#417 Remove mounted status when attacking
  src/map/packet_system.cpp
Labels: merge ready

#422 Fix buying Magicked Astrolabe
  scripts/zones/Windurst_Waters/npcs/Churano-Shurano.lua
Labels: review ready

#424 Replace tabs with 4x spaces for all files in script/.
  scripts/globals/items/shadow_lord_shirt.lua
  scripts/globals/mobskills/impale.lua
  scripts/globals/mobskills/polar_blast.lua
  scripts/globals/mobskills/pyric_blast.lua
  scripts/globals/mobskills/winter_breeze.lua
  scripts/globals/spells/bio_iii.lua
  scripts/globals/spells/invisible.lua
  scripts/globals/spells/sneak.lua
  scripts/globals/survival_guide.lua
  scripts/zones/Horlais_Peak/mobs/Cottontail.lua
  scripts/zones/Mhaura/npcs/Laughing_Bison.lua
  scripts/zones/Port_Bastok/npcs/Ominous_Cloud.lua
  scripts/zones/Southern_San_dOria/npcs/Ominous_Cloud.lua
  scripts/zones/The_Ashu_Talif/mobs/Gowam.lua
  scripts/zones/Upper_Delkfutts_Tower/mobs/Mimas.lua
  scripts/zones/Wajaom_Woodlands/mobs/Vulpangue.lua
  scripts/zones/Windurst_Woods/npcs/Ominous_Cloud.lua
Labels: merge ready

#427 Update russian comments to english for some src/ sub-directories.
  documentation/ZoneIDs.txt
  src/common/lua/lunar.h
  src/common/mmo.h
  src/common/utils.cpp
  src/common/utils.h
  src/login/lobby.cpp
  src/search/data_loader.cpp
  src/search/packets/auction_history.cpp
  src/search/packets/auction_list.cpp
  src/search/packets/linkshell_list.cpp
  src/search/packets/party_list.cpp
  src/search/packets/search_list.cpp
  src/search/search.cpp
  src/search/tcp_request.cpp
Labels: merge ready

#410 Add the `BaseSell` value for Spool of Wyrdstrand.
  sql/item_basic.sql
Labels: hold, reviewed

#431 Claim updates
  scripts/mixins/families/aern.lua
  src/map/ai/controllers/mob_controller.cpp
  src/map/ai/states/ability_state.cpp
  src/map/ai/states/magic_state.cpp
  src/map/entities/battleentity.cpp
  src/map/entities/charentity.cpp
  src/map/entities/charentity.h
  src/map/entities/mobentity.cpp
  src/map/entities/mobentity.h
  src/map/utils/battleutils.cpp
  src/map/utils/battleutils.h
  src/map/utils/charutils.cpp
  src/map/zone_entities.cpp
Labels: reviewed

#433 Fix gil split with treasure chests
  scripts/globals/treasure.lua
Labels: merge ready

#434 Mystery box additions
  scripts/zones/Windurst_Walls/npcs/Arbitrix.lua
  src/map/daily_system.cpp
  src/map/daily_system.h
  src/map/lua/lua_baseentity.cpp
  src/map/lua/luautils.cpp
  src/map/lua/luautils.h
  src/map/map.cpp
Labels: reviewed

#419 make all NMs not charmable
  src/map/instance_loader.cpp
  src/map/utils/mobutils.cpp
  src/map/utils/zoneutils.cpp
Labels: reviewed

#444 Fix new GCC warning in Trust branch
  src/map/entities/battleentity.h
  src/map/entities/charentity.h
  src/map/lua/lua_baseentity.cpp
Labels: merge ready
