Repository project-topaz/topaz, pull requests merged in 2020-05, with the labels that each got.

#454 Trust Spell Casting
  scripts/globals/gambits.lua
  scripts/globals/spells/trust/curilla.lua
  scripts/globals/spells/trust/excenmille.lua
  scripts/globals/spells/trust/kupipi.lua
  scripts/globals/spells/trust/naji.lua
  scripts/globals/spells/trust/shantotto.lua
  sql/mob_spell_lists.sql
  src/map/ai/controllers/trust_controller.cpp
  src/map/ai/controllers/trust_controller.h
  src/map/ai/helpers/gambits_container.cpp
  src/map/ai/helpers/gambits_container.h
  src/map/entities/baseentity.h
  src/map/entities/battleentity.h
  src/map/entities/trustentity.cpp
  src/map/entities/trustentity.h
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/mob_spell_container.cpp
  src/map/mob_spell_container.h
  src/map/spell.cpp
  src/map/spell.h
  src/map/utils/battleutils.cpp
  src/map/utils/battleutils.h
  win32/vcxproj/topaz_game.vcxproj
  win32/vcxproj/topaz_game.vcxproj.filters
Labels: review ready

#568 Casket fix
  scripts/globals/caskets.lua
  scripts/mixins/spawn_casket.lua
Labels: merge ready

#554 Update COR AF quest timer to current retail.
  scripts/zones/Wajaom_Woodlands/npcs/Leypoint.lua
Labels: merge ready

#530 Remove FR server message
  conf/default/server_message_fr.conf
  src/map/lua/luautils.cpp
  src/map/map.cpp
  src/map/map.h
  src/map/packet_system.cpp
Labels: merge ready

#560 Add range check to wyvern's Healing Breath
  scripts/globals/pets/wyvern.lua
Labels: merge ready

#546 Fixes Thuban and Herensegue's WS.
  sql/mob_skill_lists.sql
Labels: merge ready

#563 Stop tame applying enmity on success
  scripts/globals/abilities/tame.lua
  sql/abilities.sql
Labels: merge ready

#586 Fix Typo in Porter Moogle Slip 18
  scripts/globals/porter_moogle_util.lua
Labels: merge ready

#579 Update rolanberry_faifuku/+1
  scripts/globals/items/rolanberry_daifuku.lua
  scripts/globals/items/rolanberry_daifuku_+1.lua
Labels: merge ready

#550 Adds timer to spawn for Knight Crabs in Jugner.
  scripts/zones/Jugner_Forest/Zone.lua
  scripts/zones/Jugner_Forest/mobs/King_Arthro.lua
  sql/mob_groups.sql
Labels: merge ready

#565 Elemental Dots functional with BLM merited abilities. Dot, and stat d…
  scripts/globals/effects/burn.lua
  scripts/globals/effects/choke.lua
  scripts/globals/effects/drown.lua
  scripts/globals/effects/frost.lua
  scripts/globals/effects/rasp.lua
  scripts/globals/effects/shock.lua
  scripts/globals/magic.lua
  scripts/globals/spells/burn.lua
  scripts/globals/spells/choke.lua
  scripts/globals/spells/drown.lua
  scripts/globals/spells/frost.lua
  scripts/globals/spells/rasp.lua
  scripts/globals/spells/shock.lua
Labels: merge ready

#573 Caskets: Split area loot
  scripts/globals/casket_loot.lua
  scripts/globals/caskets.lua
Labels: merge ready

#574 Make Cactrot go Rapido again!
  scripts/zones/Eastern_Altepa_Desert/mobs/Cactrot_Rapido.lua
  sql/mob_pool_mods.sql
  sql/mob_spawn_mods.sql
Labels: merge ready

#564 Quest: Tuning In
  scripts/zones/Windurst_Waters/npcs/Leepe-Hoppe.lua
Labels: merge ready

#561 ROV Chapter 1 mob moves
  scripts/globals/mobskills/bonebreaking_barrage.lua
  scripts/globals/mobskills/calcifying_claw.lua
  scripts/globals/mobskills/clarsach_call.lua
  scripts/globals/mobskills/divesting_stampede.lua
  scripts/globals/mobskills/entice.lua
  scripts/globals/mobskills/hellfire_arrow.lua
  scripts/globals/mobskills/hysteric_assault.lua
  scripts/globals/mobskills/incensed_pummel.lua
  scripts/globals/mobskills/lunatic_voice.lua
  scripts/globals/mobskills/sonic_buffet.lua
  scripts/globals/mobskills/soulshattering_roar.lua
  scripts/zones/Yuhtunga_Jungle/mobs/Siren.lua
  sql/mob_skill_lists.sql
  sql/mob_skills.sql
Labels: merge ready

#592 update batch tools
  tools/Database_initial_setup.cmd
  tools/Database_update.cmd
Labels: merge ready

#587 Add configurable multiplier for normally-dropped gil
  conf/default/map.conf
  src/map/entities/mobentity.cpp
  src/map/map.cpp
  src/map/map.h
  src/map/utils/charutils.cpp
Labels: merge ready

#549 Change auto add master on UpdateEnmity
  src/map/ai/states/mobskill_state.cpp
  src/map/enmity_container.h
Labels: merge ready

#575 Add key trading to mystery box
  scripts/globals/gobbiemysterybox.lua
  scripts/zones/Aht_Urhgan_Whitegate/npcs/Wondrix.lua
  scripts/zones/Bastok_Markets/npcs/Specilox.lua
  scripts/zones/Bastok_Mines/npcs/Bountibox.lua
  scripts/zones/Lower_Jeuno/npcs/Sweepstox.lua
  scripts/zones/Port_San_dOria/npcs/Habitox.lua
  scripts/zones/Southern_San_dOria/npcs/Mystrix.lua
  scripts/zones/Upper_Jeuno/npcs/Priztrix.lua
  scripts/zones/Windurst_Walls/npcs/Arbitrix.lua
  scripts/zones/Windurst_Woods/npcs/Funtrox.lua
Labels: focus, merge ready

#591 Add Threnody II + add NM Siren's spell list
  scripts/globals/spells/dark_threnody_ii.lua
  scripts/globals/spells/earth_threnody_ii.lua
  scripts/globals/spells/fire_threnody_ii.lua
  scripts/globals/spells/ice_threnody_ii.lua
  scripts/globals/spells/light_threnody_ii.lua
  scripts/globals/spells/lightning_threnody_ii.lua
  scripts/globals/spells/water_threnody_ii.lua
  scripts/globals/spells/wind_threnody_ii.lua
  sql/mob_pools.sql
  sql/mob_spell_lists.sql
  sql/spell_list.sql
Labels: merge ready

#559 FadedPromises Bastok Quest
  scripts/globals/treasure.lua
  scripts/zones/Metalworks/npcs/Alois.lua
  scripts/zones/Metalworks/npcs/Ayame.lua
  scripts/zones/Metalworks/npcs/Romualdo.lua
  scripts/zones/Port_Bastok/npcs/Kagetora.lua
Labels: merge ready

#570 Add configurable subjob cap ratio..
  conf/default/map.conf
  src/map/entities/battleentity.cpp
  src/map/map.cpp
  src/map/map.h
Labels: merge ready

#581 ensure trust spells are level appropriate
  src/map/ai/helpers/gambits_container.cpp
  src/map/mob_spell_container.cpp
  src/map/mob_spell_container.h
  src/map/spell.cpp
Labels: merge ready

#583 Fix chain exp applying to non-chained kills.
  src/map/utils/charutils.cpp
Labels: merge ready

#558 Fixed some map quests
  scripts/zones/Northern_San_dOria/npcs/Aurege.lua
  scripts/zones/Port_Bastok/npcs/Gudav.lua
  scripts/zones/Tavnazian_Safehold/npcs/Pradiulot.lua
Labels: reviewed

#582 Added intro to teamwork questline
  scripts/zones/West_Ronfaure/npcs/Vilatroire.lua
Labels: merge ready

#609 Add lauan shield to Carautia
  scripts/zones/Southern_San_dOria/npcs/Carautia.lua
Labels: merge ready

#545 Blue Mage Transformations quest + other 3 armor pieces
  scripts/globals/mobskills/reprobation.lua
  scripts/globals/quests.lua
  scripts/zones/Aht_Urhgan_Whitegate/IDs.lua
  scripts/zones/Aht_Urhgan_Whitegate/npcs/Imperial_Whitegate.lua
  scripts/zones/Aht_Urhgan_Whitegate/npcs/Lathuya.lua
  scripts/zones/Aht_Urhgan_Whitegate/npcs/Waoud.lua
  scripts/zones/Alzadaal_Undersea_Ruins/IDs.lua
  scripts/zones/Alzadaal_Undersea_Ruins/Zone.lua
  scripts/zones/Alzadaal_Undersea_Ruins/mobs/Nepionic_Soulflayer.lua
  scripts/zones/Alzadaal_Undersea_Ruins/npcs/21.lua
  sql/mob_pools.sql
  sql/mob_skill_lists.sql
  sql/mob_skills.sql
Labels: focus, merge ready

#585 Fixed issue #325
  scripts/globals/weaponskills.lua
Labels: hold

#608 Fix OP teleporter event params
  scripts/globals/conquest.lua
Labels: merge ready

#620 adjust some mob pools that had 0 combat delay
  sql/mob_groups.sql
  sql/mob_pools.sql
Labels: merge ready

#535 Apply Tonberry and Fomor hate to alliance members in zone
  scripts/mixins/families/tonberry.lua
  scripts/mixins/fomor_hate.lua
Labels: merge ready

#634 Table some shared mission IDs
  scripts/globals/bcnm.lua
  scripts/globals/missions.lua
  scripts/zones/Altar_Room/npcs/Magicite.lua
  scripts/zones/Chateau_dOraguille/npcs/Halver.lua
  scripts/zones/FeiYin/Zone.lua
  scripts/zones/Hall_of_the_Gods/npcs/Shimmering_Circle.lua
  scripts/zones/Heavens_Tower/npcs/Rakano-Marukano.lua
  scripts/zones/Lower_Jeuno/npcs/Aldo.lua
  scripts/zones/Metalworks/npcs/Mythily.lua
  scripts/zones/Monastic_Cavern/npcs/Magicite.lua
  scripts/zones/Northern_San_dOria/npcs/Beriphaule.lua
  scripts/zones/Quicksand_Caves/npcs/qm4.lua
  scripts/zones/Quicksand_Caves/npcs/qm6.lua
  scripts/zones/Qulun_Dome/npcs/Magicite.lua
  scripts/zones/RuLude_Gardens/npcs/_6r9.lua
  scripts/zones/Throne_Room/bcnms/shadow_lord_battle.lua
  scripts/zones/Throne_Room/npcs/_4l1.lua
Labels: merge ready

#648 Orctrap placeholder was incorrect
  scripts/zones/Carpenters_Landing/IDs.lua
Labels: merge ready

#636 Tier-0 players can only delivery box in zones with AH or MH
  src/map/packet_system.cpp
Labels: merge ready

#630 Fix incorrect Goldsmithing crafting
  sql/synth_recipes.sql
Labels: merge ready

#632 Cleans up Aquillina and makes Flash in the Pan 15 minute cooldown ser…
  scripts/zones/Bastok_Markets/IDs.lua
  scripts/zones/Bastok_Markets/npcs/Aquillina.lua
Labels: merge ready
