Repository project-topaz/topaz, pull requests merged in 2020-08, with the labels that each got.

#894 Trust Stability 2
  src/map/ai/controllers/trust_controller.cpp
  src/map/ai/helpers/gambits_container.cpp
  src/map/ai/helpers/targetfind.cpp
  src/map/ai/states/magic_state.cpp
  src/map/entities/charentity.cpp
  src/map/entities/charentity.h
  src/map/entities/trustentity.cpp
  src/map/lua/lua_baseentity.cpp
  src/map/utils/battleutils.cpp
  src/map/utils/battleutils.h
  src/map/zone_entities.cpp
Labels: focus

#904 Adds drops to the Ancient Goobie
  sql/mob_droplist.sql
  sql/mob_groups.sql
Labels: approved

#915 Add onEventUpdate to some HP luas. Cost in menu now reflects Rhapsody in White KI.
  scripts/globals/homepoint.lua
  scripts/zones/Mount_Zhayolm/npcs/HomePoint#1.lua
  scripts/zones/Newton_Movalpolos/npcs/HomePoint#1.lua
  scripts/zones/Palborough_Mines/npcs/HomePoint#1.lua
  scripts/zones/Qufim_Island/npcs/HomePoint#1.lua
  scripts/zones/Xarcabard_[S]/npcs/HomePoint#1.lua
  scripts/zones/Yughott_Grotto/npcs/HomePoint#1.lua
Labels: approved

#917 Bug when retrieving crystals from Ephemeral Moogle
  scripts/globals/ephemeral.lua
Labels: approved, merge ready

#895 Check for sharpshot frame on automaton ranged attack.
  src/map/ai/controllers/automaton_controller.cpp
Labels: reviewed

#930 Fix for null item crash introduced in PR #857
  src/map/utils/charutils.cpp
Labels: approved

#730 Adds "All in the Cards" repeatable quest to Chululu
  scripts/zones/Lower_Jeuno/npcs/Chululu.lua
Labels: reviewed

#939 fix typo in IMMUNITY_DARK_SLEEP flag value
  src/map/entities/battleentity.h
Labels: approved

#941 Changes evasion to evasion skill on melody earring latents
  sql/item_latents.sql
Labels: approved

#926 Fix Master Coeurl skill set
  sql/mob_pools.sql
Labels: approved, merge ready

#944 Fix Ore Toss to only remove up to one shadow
  scripts/globals/mobskills/ore_toss.lua
Labels: approved

#942 Adjusts Calamar base drop rate to very common
  sql/mob_droplist.sql
Labels: approved

#934 Allows Smoke on the Mountain to be repeated after completion
  scripts/zones/South_Gustaberg/npcs/qm2.lua
Labels: approved

#968 Adds Tachi/+1 and Raptor Strap/+1 desynths
  sql/synth_recipes.sql
Labels: approved

#956 Pr dnc fixes
  scripts/globals/abilities/violent_flourish.lua
  scripts/globals/weaponskills.lua
Labels: approved

#955 PR: Fix NMs and battlefield mobs deaggroing
  src/map/ai/controllers/mob_controller.cpp
Labels: approved

#950 Remove incorrect script for Windy mission 1-1 cracked wall that preve…
  scripts/zones/Inner_Horutoto_Ruins/npcs/_5c0.lua
Labels: approved

#951 Add King Behemoths missing chance to enstun his melee target.
  scripts/zones/Behemoths_Dominion/mobs/King_Behemoth.lua
Labels: approved, merge ready

#954 PR: Bio now affected by RDM Enfeebling Merit Duration
  scripts/globals/spells/bio_iii.lua
Labels: approved

#933 Bug with capped skills
  src/map/utils/charutils.cpp
Labels: approved

#922 added lucid item usability
  scripts/globals/items/lucid_elixir_i.lua
  scripts/globals/items/lucid_elixir_ii.lua
  scripts/globals/items/lucid_ether_i.lua
  scripts/globals/items/lucid_ether_ii.lua
  scripts/globals/items/lucid_ether_iii.lua
  scripts/globals/items/lucid_potion_i.lua
  scripts/globals/items/lucid_potion_ii.lua
  scripts/globals/items/lucid_potion_iii.lua
  sql/item_usable.sql
Labels: approved

#962 PR: core: Fix init value for SMN Spirits.
  src/map/entities/petentity.cpp
Labels: approved

#946 Corrects Ebony Pudding spell list
  sql/mob_pools.sql
  sql/mob_spell_lists.sql
Labels: reviewed

#925 Aftermath application not damage dependant, applies before the weapon…
  scripts/globals/weaponskills/ascetics_fury.lua
  scripts/globals/weaponskills/atonement.lua
  scripts/globals/weaponskills/blade_hi.lua
  scripts/globals/weaponskills/blade_kamu.lua
  scripts/globals/weaponskills/blade_metsu.lua
  scripts/globals/weaponskills/camlanns_torment.lua
  scripts/globals/weaponskills/catastrophe.lua
  scripts/globals/weaponskills/chant_du_cygne.lua
  scripts/globals/weaponskills/cloudsplitter.lua
  scripts/globals/weaponskills/death_blossom.lua
  scripts/globals/weaponskills/drakesbane.lua
  scripts/globals/weaponskills/expiacion.lua
  scripts/globals/weaponskills/final_heaven.lua
  scripts/globals/weaponskills/garland_of_bliss.lua
  scripts/globals/weaponskills/gate_of_tartarus.lua
  scripts/globals/weaponskills/geirskogul.lua
  scripts/globals/weaponskills/insurgency.lua
  scripts/globals/weaponskills/jishnus_radiance.lua
  scripts/globals/weaponskills/kings_justice.lua
  scripts/globals/weaponskills/knights_of_round.lua
  scripts/globals/weaponskills/leaden_salute.lua
  scripts/globals/weaponskills/mandalic_stab.lua
  scripts/globals/weaponskills/mercy_stroke.lua
  scripts/globals/weaponskills/metatron_torment.lua
  scripts/globals/weaponskills/mordant_rime.lua
  scripts/globals/weaponskills/mystic_boon.lua
  scripts/globals/weaponskills/namas_arrow.lua
  scripts/globals/weaponskills/omniscience.lua
  scripts/globals/weaponskills/onslaught.lua
  scripts/globals/weaponskills/primal_rend.lua
  scripts/globals/weaponskills/pyrrhic_kleos.lua
  scripts/globals/weaponskills/quietus.lua
  scripts/globals/weaponskills/randgrith.lua
  scripts/globals/weaponskills/rudras_storm.lua
  scripts/globals/weaponskills/scourge.lua
  scripts/globals/weaponskills/stringing_pummel.lua
  scripts/globals/weaponskills/tachi_fudo.lua
  scripts/globals/weaponskills/tachi_kaiten.lua
  scripts/globals/weaponskills/tachi_rana.lua
  scripts/globals/weaponskills/torcleaver.lua
  scripts/globals/weaponskills/trueflight.lua
  scripts/globals/weaponskills/ukkos_fury.lua
  scripts/globals/weaponskills/victory_smite.lua
  scripts/globals/weaponskills/vidohunir.lua
  scripts/globals/weaponskills/wildfire.lua
Labels: approved

#812 Fix for LoadPet iteration not working with gaps in pet_list ID's
  src/map/utils/petutils.cpp
Labels: approved

#923 prevent server crash when targeting NPC and using !tp !hp !mp
  scripts/commands/hp.lua
  scripts/commands/mp.lua
  scripts/commands/tp.lua
Labels: approved

#959 PR: Pets should not be gaining MOB TP
  src/map/utils/battleutils.cpp
Labels: reviewed

#881 Create MOD for "Resistance to All Status Ailments"
  scripts/globals/magic.lua
  scripts/globals/status.lua
  sql/item_mods.sql
  src/map/modifier.h
Labels: approved

#851 [Blue Mage] Fix assimilation merit
  src/map/packets/menu_merit.cpp
Labels: focus, reviewed

#780 Trust Advanced Gambits
  scripts/globals/gambits.lua
  scripts/globals/mobskills/king_cobra_clamp.lua
  scripts/globals/spells/trust/ajido-marujido.lua
  scripts/globals/spells/trust/ayame.lua
  scripts/globals/spells/trust/curilla.lua
  scripts/globals/spells/trust/excenmille.lua
  scripts/globals/spells/trust/iron_eater.lua
  scripts/globals/spells/trust/kupipi.lua
  scripts/globals/spells/trust/naji.lua
  scripts/globals/spells/trust/nanaa_mihgo.lua
  scripts/globals/spells/trust/shantotto.lua
  scripts/globals/spells/trust/shantotto_ii.lua
  scripts/globals/spells/trust/trion.lua
  scripts/globals/spells/trust/volker.lua
  scripts/globals/spells/trust/zeid_ii.lua
  src/map/ai/controllers/trust_controller.cpp
  src/map/ai/helpers/gambits_container.cpp
  src/map/ai/helpers/gambits_container.h
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
Labels: focus

#1006 RoE repeat records + bug fixes
  scripts/globals/mobs.lua
  scripts/globals/npc_util.lua
  scripts/globals/settings.lua
  scripts/globals/sparkshop.lua
  scripts/zones/Windurst_Woods/npcs/Fhelm_Jobeizat.lua
  src/map/lua/lua_baseentity.cpp
Labels: reviewed

#989 Uragnite mixin
  scripts/mixins/families/uragnite.lua
  scripts/zones/Bibiki_Bay/mobs/Coralline_Uragnite.lua
  scripts/zones/Dynamis-Buburimu/mobs/Nightmare_Uragnite.lua
  sql/mob_skill_lists.sql
Labels: reviewed

#1010 Implements several ring desynths
  sql/synth_recipes.sql
Labels: reviewed

#1015 local those variables..
  scripts/globals/summon.lua
Labels: approved, reviewed

#1012 Fix Dancing Chains to apply drown only in a 10y radius
  scripts/globals/mobskills/dancing_chains.lua
Labels: approved, reviewed

#1018 Overlord Bakgodek loot fixes
  sql/mob_droplist.sql
Labels: reviewed

#1016 Small change to Python requirements.txt file.
  tools/requirements.txt
Labels: reviewed

#1024 Adds scripting for Azure Lore ability to give the effect.
  scripts/globals/abilities/azure_lore.lua
Labels: reviewed

#987 fov_allow_alliance (conf setting) --> REGIME_REWARD_ALLIANCE (lua setting)
  conf/default/map.conf
  scripts/globals/regimes.lua
  scripts/globals/settings.lua
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/map.cpp
  src/map/map.h
Labels: approved, reviewed
