Repository project-topaz/topaz, pull requests merged in 2020-04, with the labels that each got.

#447 Fix pet claiming on initial hit
  src/map/ai/states/ability_state.cpp
  src/map/ai/states/magic_state.cpp
  src/map/entities/battleentity.cpp
  src/map/entities/mobentity.cpp
Labels: reviewed

#438 This *should* fix Guivre's ability to walk around
  scripts/zones/Kuftal_Tunnel/mobs/Guivre.lua
Labels: merge ready

#445 Move version.info
  .gitignore
  conf/default/version.conf
  src/login/login.cpp
Labels: merge ready

#451 mob UDMG fixes
  scripts/zones/Dynamis-Xarcabard/mobs/Yang.lua
  scripts/zones/Dynamis-Xarcabard/mobs/Ying.lua
  scripts/zones/Wajaom_Woodlands/mobs/Tinnin.lua
Labels: merge ready

#452 Fixed Evisceration WS Quest
  scripts/zones/Gustav_Tunnel/IDs.lua
  scripts/zones/Kazham/npcs/Jakoh_Wahcondalo.lua
Labels: merge ready

#466 Trust Spell and Skill List SQL Reservation (and Mob Pools)
  sql/mob_pools.sql
  sql/mob_skill_lists.sql
  sql/mob_spell_lists.sql
Labels: merge ready

#450 Trust Movement, Positioning, Enmity Tracking & Combat Engagement
  scripts/globals/trust.lua
  src/map/ai/controllers/trust_controller.cpp
  src/map/ai/controllers/trust_controller.h
  src/map/latent_effect_container.cpp
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/utils/trustutils.cpp
Labels: reviewed

#469 Fixed and added some BaseSell prices.
  sql/item_basic.sql
Labels: merge ready

#346 Add `Pinecone Bomb` blue magic spell.
  scripts/globals/bluemagic.lua
  scripts/globals/spells/bluemagic/pinecone_bomb.lua
Labels: focus, merge ready, research needed

#453 Claim drop grace period
  src/map/ai/controllers/mob_controller.cpp
  src/map/ai/controllers/mob_controller.h
  src/map/entities/charentity.cpp
  src/map/utils/battleutils.cpp
Labels: merge ready

#467 Remove some left-over code from the mage merit changes
  scripts/globals/magic.lua
  scripts/globals/spells/bio.lua
  scripts/globals/spells/bio_ii.lua
  scripts/globals/spells/bio_iii.lua
  scripts/globals/spells/blind_ii.lua
  scripts/globals/spells/dia_iii.lua
  scripts/globals/spells/doton_san.lua
  scripts/globals/spells/huton_san.lua
  scripts/globals/spells/hyoton_san.lua
  scripts/globals/spells/katon_san.lua
  scripts/globals/spells/paralyze_ii.lua
  scripts/globals/spells/phalanx.lua
  scripts/globals/spells/phalanx_ii.lua
  scripts/globals/spells/raiton_san.lua
  scripts/globals/spells/shellra_v.lua
  scripts/globals/spells/slow_ii.lua
  scripts/globals/spells/suiton_san.lua
Labels: merge ready

#468 Fix Lumber Jack spawn. Always spawns after Weeping Willow is defeated.
  scripts/zones/Batallia_Downs/mobs/Weeping_Willow.lua
Labels: merge ready

#471 Fix issues with multi phase bcnms
  scripts/globals/battlefield.lua
  scripts/zones/Empyreal_Paradox/bcnms/dawn.lua
  scripts/zones/Empyreal_Paradox/mobs/Promathia.lua
  scripts/zones/Empyreal_Paradox/mobs/Promathia_2.lua
  scripts/zones/Full_Moon_Fountain/bcnms/moon_reading.lua
  scripts/zones/Full_Moon_Fountain/mobs/Tatzlwurm.lua
  scripts/zones/Full_Moon_Fountain/mobs/Yali.lua
  scripts/zones/QuBia_Arena/bcnms/heir_to_the_light.lua
  scripts/zones/QuBia_Arena/mobs/Death_Clan_Destroyer.lua
  scripts/zones/QuBia_Arena/mobs/Rallbrog_of_Clan_Death.lua
  scripts/zones/QuBia_Arena/mobs/Rojgnojs_Left_Hand.lua
  scripts/zones/QuBia_Arena/mobs/Rojgnojs_Right_Hand.lua
  scripts/zones/QuBia_Arena/mobs/Vangknok_of_Clan_Death.lua
  scripts/zones/QuBia_Arena/mobs/Warlord_Rojgnoj.lua
  scripts/zones/QuBia_Arena/mobs/Worgbut_of_Clan_Death.lua
  scripts/zones/QuBia_Arena/mobs/Yukvok_of_Clan_Death.lua
  scripts/zones/Sealions_Den/bcnms/one_to_be_feared.lua
  scripts/zones/Sealions_Den/mobs/Mammet-22_Zeta.lua
  scripts/zones/Sealions_Den/mobs/Omega.lua
  scripts/zones/Sealions_Den/mobs/Ultima.lua
  scripts/zones/Sealions_Den/npcs/Airship_Door.lua
  scripts/zones/The_Celestial_Nexus/bcnms/celestial_nexus.lua
  scripts/zones/The_Celestial_Nexus/mobs/Ealdnarche_2.lua
  scripts/zones/Throne_Room/IDs.lua
  scripts/zones/Throne_Room/bcnms/shadow_lord_battle.lua
  scripts/zones/Throne_Room/bcnms/where_two_paths_converge.lua
  scripts/zones/Throne_Room/mobs/Shadow_Lord.lua
  scripts/zones/Throne_Room/mobs/Zeid.lua
  scripts/zones/Throne_Room/mobs/Zeid_2.lua
Labels: merge ready

#477 QoL for Moongate
  scripts/zones/RoMaeve/Zone.lua
Labels: merge ready

#464 Add Elemental Sforzo placeholder, to make the ability usable.
  scripts/globals/abilities/elemental_sforzo.lua
  sql/abilities.sql
Labels: merge ready

#465 Upgrade !hp, !mp and !tp commands
  scripts/commands/hp.lua
  scripts/commands/mp.lua
  scripts/commands/tp.lua
Labels: merge ready

#462 Add Rune Fencer unlock quest "Children of the Rune".
  scripts/zones/Eastern_Adoulin/IDs.lua
  scripts/zones/Eastern_Adoulin/npcs/Octavien.lua
  scripts/zones/Yahse_Hunting_Grounds/npcs/Yahse_Wildflower.lua
Labels: merge ready

#482 Add family column to spell_list
  migrations/migrate.py
  migrations/spell_family_column.py
  scripts/globals/magic.lua
  sql/spell_list.sql
  src/map/spell.cpp
  src/map/spell.h
Labels: merge ready

#483 Check if enmity list is empty for unclaimed mobs
  src/map/ai/states/mobskill_state.cpp
  src/map/entities/battleentity.cpp
  src/map/entities/charentity.cpp
  src/map/entities/mobentity.cpp
  src/map/utils/battleutils.cpp
  src/map/utils/battleutils.h
Labels: merge ready

#506 added missing import
  migrations/migrate.py
Labels: merge ready

#518 Misc. updates and additions.
  scripts/globals/settings.lua
  scripts/zones/Bastok_Markets/Zone.lua
  scripts/zones/Bastok_Mines/Zone.lua
  scripts/zones/Northern_San_dOria/Zone.lua
  scripts/zones/Port_Bastok/Zone.lua
  scripts/zones/Port_San_dOria/Zone.lua
  scripts/zones/Port_Windurst/Zone.lua
  scripts/zones/Southern_San_dOria/Zone.lua
  scripts/zones/Windurst_Waters/Zone.lua
  scripts/zones/Windurst_Woods/Zone.lua
  sql/abilities.sql
  sql/item_basic.sql
  sql/item_equipment.sql
Labels: merge ready

#499 Fix AH 7-item limit not being enforced correctly
  conf/default/map.conf
  src/map/map.cpp
  src/map/map.h
  src/map/packet_system.cpp
Labels: merge ready

#500 Add config flag to dis/allow new accounts
  conf/default/login.conf
  src/login/login.cpp
  src/login/login.h
  src/login/login_auth.cpp
Labels: merge ready

#511 Add a system message when using `!setGil` command
  scripts/commands/setgil.lua
Labels: merge ready

#507 abilities.sql audit for CE and VE values
  sql/abilities.sql
Labels: reviewed

#522 Add ON ZONE removal flag for dynamis effect.
  sql/status_effects.sql
Labels: merge ready

#526 Fix for DNC closed position
  sql/traits.sql
Labels: merge ready

#503 Kohlo-Lakolo Rewrite with minor changes to related NPC.
  scripts/zones/Port_Windurst/npcs/Kohlo-Lakolo.lua
  scripts/zones/Port_Windurst/npcs/Pichichi.lua
  scripts/zones/Windurst_Walls/npcs/_6n2.lua
Labels: merge ready

#517 Some crafting fixes
  src/map/utils/synthutils.cpp
Labels: merge ready

#521 Fixed tutorial NPCs saying wrong numbers
  scripts/quests/tutorial.lua
Labels: merge ready

#529 Update CoP mission IDs to retail and expand mission log
  migrations/cop_mission_ids.py
  migrations/migrate.py
  migrations/mission_blob_extra.py
  scripts/globals/missions.lua
  src/common/mmo.h
  src/map/entities/charentity.cpp
  src/map/entities/charentity.h
  src/map/lua/lua_baseentity.cpp
  src/map/lua/lua_baseentity.h
  src/map/packets/quest_mission_log.cpp
Labels: merge ready

#534 Update default settings
  conf/default/map.conf
  scripts/globals/homepoint.lua
  scripts/globals/settings.lua
  scripts/globals/status.lua
  src/map/entities/baseentity.cpp
  src/map/entities/battleentity.cpp
Labels: merge ready

#537 added brass zaghnal desynth recipe
  sql/synth_recipes.sql
Labels: merge ready

#539 Mazurka Fix
  sql/status_effects.sql
  sql/zone_settings.sql
Labels: merge ready
